import type { FlightInfo, DateItem } from './types'

export const dateList: DateItem[] = [
  { label: '今天', date: '05-23', fullDate: '2026-05-23' },
  { label: '明天', date: '24', fullDate: '2026-05-24' },
  { label: '后天', date: '25', fullDate: '2026-05-25' },
  { label: '周二', date: '26', fullDate: '2026-05-26' },
  { label: '周三', date: '27', fullDate: '2026-05-27' },
  { label: '周四', date: '28', fullDate: '2026-05-28' },
  { label: '周五', date: '29', fullDate: '2026-05-29' },
  { label: '周六', date: '30', fullDate: '2026-05-30' },
  { label: '周日', date: '31', fullDate: '2026-05-31' },
  { label: '周一', date: '06-01', fullDate: '2026-06-01' },
  { label: '周二', date: '02', fullDate: '2026-06-02' },
  { label: '周三', date: '03', fullDate: '2026-06-03' },
  { label: '周四', date: '04', fullDate: '2026-06-04' },
  { label: '周五', date: '05', fullDate: '2026-06-05' },
  { label: '周六', date: '06', fullDate: '2026-06-06' },
]

export const mockFlightList: FlightInfo[] = [
  {
    flightNo: 'CA1563',
    airline: '国航',
    airlineColor: '#E60012',
    departureTime: '19:30',
    arrivalTime: '21:50',
    departureAirport: '首都T3',
    arrivalAirport: '虹桥T2',
    duration: '2h20m',
    aircraftType: '空客33A',
    aircraftSize: '大',
    mealService: true,
    price: 926,
    cabinClass: '经济舱',
    discount: '4.3折',
    intervalDay: 0,
  },
  {
    flightNo: 'CZ8803',
    airline: '南航',
    airlineColor: '#0066B3',
    departureTime: '20:00',
    arrivalTime: '22:10',
    departureAirport: '大兴',
    arrivalAirport: '虹桥T2',
    duration: '2h10m',
    aircraftType: '空客327',
    aircraftSize: '中',
    mealService: true,
    price: 360,
    cabinClass: '经济舱',
    discount: '2.2折',
    intervalDay: 0,
  },
  {
    flightNo: 'CA1589',
    airline: '国航',
    airlineColor: '#E60012',
    departureTime: '20:30',
    arrivalTime: '22:40',
    departureAirport: '首都T3',
    arrivalAirport: '虹桥T2',
    duration: '2h10m',
    aircraftType: '波音789',
    aircraftSize: '大',
    mealService: true,
    price: 926,
    cabinClass: '经济舱',
    discount: '4.3折',
    intervalDay: 0,
  },
  {
    flightNo: 'MU9192',
    airline: '东航',
    airlineColor: '#CE0E2D',
    departureTime: '20:45',
    arrivalTime: '23:10',
    departureAirport: '大兴',
    arrivalAirport: '虹桥T2',
    duration: '2h25m',
    aircraftType: 'C919',
    aircraftSize: '中',
    mealService: true,
    price: 1980,
    cabinClass: '商务舱',
    discount: '2.4折',
    intervalDay: 0,
  },
  {
    flightNo: 'HO1254',
    airline: '吉祥',
    airlineColor: '#E60012',
    departureTime: '22:10',
    arrivalTime: '00:20',
    departureAirport: '大兴',
    arrivalAirport: '浦东T2',
    duration: '2h10m',
    aircraftType: '空客32A',
    aircraftSize: '中',
    mealService: true,
    price: 730,
    cabinClass: '经济舱',
    discount: '4.1折',
    intervalDay: 1,
  },
  {
    flightNo: 'CZ8882',
    airline: '南航',
    airlineColor: '#0066B3',
    departureTime: '22:20',
    arrivalTime: '00:30',
    departureAirport: '大兴',
    arrivalAirport: '浦东T2',
    duration: '2h10m',
    aircraftType: '空客32J',
    aircraftSize: '中',
    mealService: true,
    price: 360,
    cabinClass: '经济舱',
    discount: '2.2折',
    intervalDay: 1,
  },
  {
    flightNo: 'CA1831',
    airline: '国航',
    airlineColor: '#E60012',
    departureTime: '07:30',
    arrivalTime: '09:50',
    departureAirport: '首都T3',
    arrivalAirport: '虹桥T2',
    duration: '2h20m',
    aircraftType: '波音737',
    aircraftSize: '中',
    mealService: true,
    price: 680,
    cabinClass: '经济舱',
    discount: '3.5折',
    intervalDay: 0,
  },
  {
    flightNo: 'MU5101',
    airline: '东航',
    airlineColor: '#CE0E2D',
    departureTime: '08:00',
    arrivalTime: '10:15',
    departureAirport: '大兴',
    arrivalAirport: '虹桥T2',
    duration: '2h15m',
    aircraftType: '空客320',
    aircraftSize: '中',
    mealService: true,
    price: 550,
    cabinClass: '经济舱',
    discount: '3.0折',
    intervalDay: 0,
  },
]
