/* eslint-disable @typescript-eslint/no-explicit-any */
import { useNavigate } from 'react-router'
import { List } from '@lynx-js/lynx-ui'
import { useCallback, useMainThreadRef } from '@lynx-js/react'
import type { FlightOrder } from 'travel-domain';
import { useFlightStore } from '../../store'
import { INavbarRef, NavBar } from '../../components/NavBar'
import { useScrollOpacity } from '../../hooks/useScrollOpacity'

import './index.scss';

// 从 flightNo 前缀推导航司中文名（如 CA1234 -> 国航）
const AIRLINE_NAME_MAP: Record<string, string> = {
  CA: '国航',
  MU: '东航',
  CZ: '南航',
  HU: '海航',
  MF: '厦航',
  ZH: '深航',
  '3U': '川航',
  SC: '山航',
};

function getAirlineName(flightNo: string): string {
  const prefix = flightNo.slice(0, 2);
  return AIRLINE_NAME_MAP[prefix] ?? '';
}

export function OrderList() {
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const { selectedFlight } = useFlightStore();
  const navigate = useNavigate();

  const navBarRef = useMainThreadRef<INavbarRef>(null)

  const setNavBarOpacityMT = useCallback((opacity: number) => {
    'main thread';
    if (navBarRef.current) {
      navBarRef.current.setOpacity(opacity)
    }
  }, [navBarRef])

  const { opacity, inverseOpacity, handleScrollMT } = useScrollOpacity({
    threshold: 100,
    startOpacity: 0,
    endOpacity: 1,
    setStyleMT: setNavBarOpacityMT,
  })

  const handleOrderTap = useCallback((order: FlightOrder) => {
    navigate(`/orderDetail/${order.orderBaseId}`);
  }, [navigate])

  // Mock orders（字段以 travel-domain 的 FlightOrder 为准）
  const orders: FlightOrder[] = [
    {
      orderSource: 1,
      orderBaseId: 'ORDER_001',
      flightOrderNo: 'CA123400123456',
      flightOrderType: 'FLIGHT',
      flightOrderStatus: '已完成',
      refundStatus: '0',
      refundAmount: 0,
      payExpireTime: '',
      fromCityCode: 'BJS',
      fromCityName: '北京',
      toCityCode: 'SHA',
      toCityName: '上海',
      tripType: '1',
      fromDate: '8月31日 周五',
      returnDate: '',
      totalAmount: 680,
      payAmount: '680',
      departTime: '08:00',
      arriveTime: '10:30',
      durationTime: '2h30m',
      departAirportName: '首都国际机场',
      departTerminal: 'T3',
      arriveAirportName: '浦东国际机场',
      arriveTerminal: 'T2',
      flightNo: 'CA1234',
      stops: '0',
      createTime: '2024-08-25 14:30:00',
      contactName: '张三',
    },
    {
      orderSource: 1,
      orderBaseId: 'ORDER_002',
      flightOrderNo: 'MU567800234567',
      flightOrderType: 'FLIGHT',
      flightOrderStatus: '待出行',
      refundStatus: '0',
      refundAmount: 0,
      payExpireTime: '2024-09-04 23:59:59',
      fromCityCode: 'SHA',
      fromCityName: '上海',
      toCityCode: 'CAN',
      toCityName: '广州',
      tripType: '1',
      fromDate: '9月5日 周三',
      returnDate: '',
      totalAmount: 720,
      payAmount: '720',
      departTime: '09:30',
      arriveTime: '12:00',
      durationTime: '2h30m',
      departAirportName: '虹桥国际机场',
      departTerminal: 'T2',
      arriveAirportName: '白云国际机场',
      arriveTerminal: 'T1',
      flightNo: 'MU5678',
      stops: '0',
      createTime: '2024-08-28 10:15:00',
      contactName: '李四',
    },
    {
      orderSource: 1,
      orderBaseId: 'ORDER_003',
      flightOrderNo: 'CZ901200345678',
      flightOrderType: 'FLIGHT',
      flightOrderStatus: '待出行',
      refundStatus: '0',
      refundAmount: 0,
      payExpireTime: '2024-09-07 23:59:59',
      fromCityCode: 'CAN',
      fromCityName: '广州',
      toCityCode: 'CTU',
      toCityName: '成都',
      tripType: '1',
      fromDate: '9月8日 周六',
      returnDate: '',
      totalAmount: 850,
      payAmount: '850',
      departTime: '14:00',
      arriveTime: '16:30',
      durationTime: '2h30m',
      departAirportName: '白云国际机场',
      departTerminal: 'T2',
      arriveAirportName: '双流国际机场',
      arriveTerminal: 'T1',
      flightNo: 'CZ9012',
      stops: '0',
      createTime: '2024-09-01 09:20:00',
      contactName: '王五',
    },
    {
      orderSource: 1,
      orderBaseId: 'ORDER_004',
      flightOrderNo: 'HU789000456789',
      flightOrderType: 'FLIGHT',
      flightOrderStatus: '已取消',
      refundStatus: '3',
      refundAmount: 590,
      payExpireTime: '',
      fromCityCode: 'CTU',
      fromCityName: '成都',
      toCityCode: 'BJS',
      toCityName: '北京',
      tripType: '1',
      fromDate: '9月10日 周一',
      returnDate: '',
      totalAmount: 590,
      payAmount: '590',
      departTime: '10:00',
      arriveTime: '12:30',
      durationTime: '2h30m',
      departAirportName: '双流国际机场',
      departTerminal: 'T2',
      arriveAirportName: '首都国际机场',
      arriveTerminal: 'T2',
      flightNo: 'HU7890',
      stops: '0',
      createTime: '2024-09-02 16:40:00',
      contactName: '赵六',
    },
    {
      orderSource: 1,
      orderBaseId: 'ORDER_005',
      flightOrderNo: 'MF345600567890',
      flightOrderType: 'FLIGHT',
      flightOrderStatus: '已完成',
      refundStatus: '0',
      refundAmount: 0,
      payExpireTime: '',
      fromCityCode: 'XMN',
      fromCityName: '厦门',
      toCityCode: 'SHA',
      toCityName: '上海',
      tripType: '1',
      fromDate: '9月12日 周三',
      returnDate: '',
      totalAmount: 980,
      payAmount: '980',
      departTime: '15:30',
      arriveTime: '17:45',
      durationTime: '2h15m',
      departAirportName: '高崎国际机场',
      departTerminal: 'T3',
      arriveAirportName: '浦东国际机场',
      arriveTerminal: 'T1',
      flightNo: 'MF3456',
      stops: '0',
      createTime: '2024-09-05 11:00:00',
      contactName: '钱七',
    },
    {
      orderSource: 1,
      orderBaseId: 'ORDER_006',
      flightOrderNo: 'ZH456700678901',
      flightOrderType: 'FLIGHT',
      flightOrderStatus: '待出行',
      refundStatus: '0',
      refundAmount: 0,
      payExpireTime: '2024-09-14 23:59:59',
      fromCityCode: 'SZX',
      fromCityName: '深圳',
      toCityCode: 'HGH',
      toCityName: '杭州',
      tripType: '1',
      fromDate: '9月15日 周六',
      returnDate: '',
      totalAmount: 760,
      payAmount: '760',
      departTime: '11:00',
      arriveTime: '13:15',
      durationTime: '2h15m',
      departAirportName: '宝安国际机场',
      departTerminal: 'T3',
      arriveAirportName: '萧山国际机场',
      arriveTerminal: 'T2',
      flightNo: 'ZH4567',
      stops: '0',
      createTime: '2024-09-08 18:25:00',
      contactName: '孙八',
    },
    {
      orderSource: 1,
      orderBaseId: 'ORDER_007',
      flightOrderNo: '3U890100789012',
      flightOrderType: 'FLIGHT',
      flightOrderStatus: '已完成',
      refundStatus: '0',
      refundAmount: 0,
      payExpireTime: '',
      fromCityCode: 'CTU',
      fromCityName: '成都',
      toCityCode: 'SZX',
      toCityName: '深圳',
      tripType: '1',
      fromDate: '9月18日 周二',
      returnDate: '',
      totalAmount: 1120,
      payAmount: '1120',
      departTime: '13:00',
      arriveTime: '15:30',
      durationTime: '2h30m',
      departAirportName: '双流国际机场',
      departTerminal: 'T1',
      arriveAirportName: '宝安国际机场',
      arriveTerminal: 'T2',
      flightNo: '3U8901',
      stops: '0',
      createTime: '2024-09-11 09:45:00',
      contactName: '周九',
    },
    {
      orderSource: 1,
      orderBaseId: 'ORDER_008',
      flightOrderNo: 'SC234500890123',
      flightOrderType: 'FLIGHT',
      flightOrderStatus: '待出行',
      refundStatus: '0',
      refundAmount: 0,
      payExpireTime: '2024-09-19 23:59:59',
      fromCityCode: 'TAO',
      fromCityName: '青岛',
      toCityCode: 'SHA',
      toCityName: '上海',
      tripType: '1',
      fromDate: '9月20日 周四',
      returnDate: '',
      totalAmount: 650,
      payAmount: '650',
      departTime: '16:00',
      arriveTime: '18:00',
      durationTime: '2h0m',
      departAirportName: '流亭国际机场',
      departTerminal: 'T1',
      arriveAirportName: '虹桥国际机场',
      arriveTerminal: 'T2',
      flightNo: 'SC2345',
      stops: '0',
      createTime: '2024-09-13 14:20:00',
      contactName: '吴十',
    },
    {
      orderSource: 1,
      orderBaseId: 'ORDER_009',
      flightOrderNo: 'CA678900901234',
      flightOrderType: 'FLIGHT',
      flightOrderStatus: '退款中',
      refundStatus: '1',
      refundAmount: 1380,
      payExpireTime: '',
      fromCityCode: 'BJS',
      fromCityName: '北京',
      toCityCode: 'SYX',
      toCityName: '三亚',
      tripType: '1',
      fromDate: '9月22日 周六',
      returnDate: '',
      totalAmount: 1380,
      payAmount: '1380',
      departTime: '07:00',
      arriveTime: '11:00',
      durationTime: '4h0m',
      departAirportName: '首都国际机场',
      departTerminal: 'T3',
      arriveAirportName: '凤凰国际机场',
      arriveTerminal: 'T1',
      flightNo: 'CA6789',
      stops: '0',
      createTime: '2024-09-15 20:10:00',
      contactName: '郑十一',
    },
    {
      orderSource: 1,
      orderBaseId: 'ORDER_010',
      flightOrderNo: 'MU234501012345',
      flightOrderType: 'FLIGHT',
      flightOrderStatus: '已完成',
      refundStatus: '0',
      refundAmount: 0,
      payExpireTime: '',
      fromCityCode: 'SHA',
      fromCityName: '上海',
      toCityCode: 'XIY',
      toCityName: '西安',
      tripType: '1',
      fromDate: '9月25日 周二',
      returnDate: '',
      totalAmount: 820,
      payAmount: '820',
      departTime: '09:00',
      arriveTime: '11:45',
      durationTime: '2h45m',
      departAirportName: '浦东国际机场',
      departTerminal: 'T1',
      arriveAirportName: '咸阳国际机场',
      arriveTerminal: 'T2',
      flightNo: 'MU2345',
      stops: '0',
      createTime: '2024-09-18 08:30:00',
      contactName: '王十二',
    },
    {
      orderSource: 1,
      orderBaseId: 'ORDER_011',
      flightOrderNo: 'CZ345601123456',
      flightOrderType: 'FLIGHT',
      flightOrderStatus: '待出行',
      refundStatus: '0',
      refundAmount: 0,
      payExpireTime: '2024-09-27 23:59:59',
      fromCityCode: 'CAN',
      fromCityName: '广州',
      toCityCode: 'BJS',
      toCityName: '北京',
      tripType: '1',
      fromDate: '9月28日 周五',
      returnDate: '',
      totalAmount: 940,
      payAmount: '940',
      departTime: '19:00',
      arriveTime: '22:15',
      durationTime: '3h15m',
      departAirportName: '白云国际机场',
      departTerminal: 'T1',
      arriveAirportName: '大兴国际机场',
      arriveTerminal: 'T2',
      flightNo: 'CZ3456',
      stops: '0',
      createTime: '2024-09-21 13:50:00',
      contactName: '李十三',
    },
    {
      orderSource: 1,
      orderBaseId: 'ORDER_012',
      flightOrderNo: 'HU567801234567',
      flightOrderType: 'FLIGHT',
      flightOrderStatus: '已完成',
      refundStatus: '0',
      refundAmount: 0,
      payExpireTime: '',
      fromCityCode: 'BJS',
      fromCityName: '北京',
      toCityCode: 'HAK',
      toCityName: '海口',
      tripType: '1',
      fromDate: '10月1日 周一',
      returnDate: '',
      totalAmount: 1560,
      payAmount: '1560',
      departTime: '08:30',
      arriveTime: '12:00',
      durationTime: '3h30m',
      departAirportName: '首都国际机场',
      departTerminal: 'T2',
      arriveAirportName: '美兰国际机场',
      arriveTerminal: 'T1',
      flightNo: 'HU5678',
      stops: '0',
      createTime: '2024-09-24 17:00:00',
      contactName: '张十四',
    },
    {
      orderSource: 1,
      orderBaseId: 'ORDER_013',
      flightOrderNo: 'MF678901345678',
      flightOrderType: 'FLIGHT',
      flightOrderStatus: '待出行',
      refundStatus: '0',
      refundAmount: 0,
      payExpireTime: '2024-10-02 23:59:59',
      fromCityCode: 'XMN',
      fromCityName: '厦门',
      toCityCode: 'BJS',
      toCityName: '北京',
      tripType: '1',
      fromDate: '10月3日 周三',
      returnDate: '',
      totalAmount: 720,
      payAmount: '720',
      departTime: '14:30',
      arriveTime: '17:30',
      durationTime: '3h0m',
      departAirportName: '高崎国际机场',
      departTerminal: 'T4',
      arriveAirportName: '大兴国际机场',
      arriveTerminal: 'T1',
      flightNo: 'MF6789',
      stops: '0',
      createTime: '2024-09-26 10:30:00',
      contactName: '刘十五',
    },
    {
      orderSource: 1,
      orderBaseId: 'ORDER_014',
      flightOrderNo: 'ZH789001456789',
      flightOrderType: 'FLIGHT',
      flightOrderStatus: '已取消',
      refundStatus: '3',
      refundAmount: 480,
      payExpireTime: '',
      fromCityCode: 'SZX',
      fromCityName: '深圳',
      toCityCode: 'NKG',
      toCityName: '南京',
      tripType: '1',
      fromDate: '10月5日 周五',
      returnDate: '',
      totalAmount: 480,
      payAmount: '480',
      departTime: '12:00',
      arriveTime: '14:30',
      durationTime: '2h30m',
      departAirportName: '宝安国际机场',
      departTerminal: 'T3',
      arriveAirportName: '禄口国际机场',
      arriveTerminal: 'T2',
      flightNo: 'ZH7890',
      stops: '0',
      createTime: '2024-09-28 19:15:00',
      contactName: '陈十六',
    },
    {
      orderSource: 1,
      orderBaseId: 'ORDER_015',
      flightOrderNo: '3U123401567890',
      flightOrderType: 'FLIGHT',
      flightOrderStatus: '待出行',
      refundStatus: '0',
      refundAmount: 0,
      payExpireTime: '2024-10-07 23:59:59',
      fromCityCode: 'CTU',
      fromCityName: '成都',
      toCityCode: 'HGH',
      toCityName: '杭州',
      tripType: '1',
      fromDate: '10月8日 周一',
      returnDate: '',
      totalAmount: 1080,
      payAmount: '1080',
      departTime: '10:30',
      arriveTime: '13:15',
      durationTime: '2h45m',
      departAirportName: '双流国际机场',
      departTerminal: 'T2',
      arriveAirportName: '萧山国际机场',
      arriveTerminal: 'T1',
      flightNo: '3U1234',
      stops: '0',
      createTime: '2024-10-01 12:00:00',
      contactName: '杨十七',
    },
    {
      orderSource: 1,
      orderBaseId: 'ORDER_016',
      flightOrderNo: 'SC345601678901',
      flightOrderType: 'FLIGHT',
      flightOrderStatus: '退款中',
      refundStatus: '1',
      refundAmount: 690,
      payExpireTime: '',
      fromCityCode: 'TNA',
      fromCityName: '济南',
      toCityCode: 'SZX',
      toCityName: '深圳',
      tripType: '1',
      fromDate: '10月10日 周三',
      returnDate: '',
      totalAmount: 690,
      payAmount: '690',
      departTime: '15:00',
      arriveTime: '18:00',
      durationTime: '3h0m',
      departAirportName: '遥墙国际机场',
      departTerminal: 'T1',
      arriveAirportName: '宝安国际机场',
      arriveTerminal: 'T1',
      flightNo: 'SC3456',
      stops: '0',
      createTime: '2024-10-03 09:40:00',
      contactName: '赵十八',
    },
    {
      orderSource: 1,
      orderBaseId: 'ORDER_017',
      flightOrderNo: 'CA890101789012',
      flightOrderType: 'FLIGHT',
      flightOrderStatus: '已完成',
      refundStatus: '0',
      refundAmount: 0,
      payExpireTime: '',
      fromCityCode: 'BJS',
      fromCityName: '北京',
      toCityCode: 'WUH',
      toCityName: '武汉',
      tripType: '1',
      fromDate: '10月12日 周五',
      returnDate: '',
      totalAmount: 1240,
      payAmount: '1240',
      departTime: '11:00',
      arriveTime: '13:15',
      durationTime: '2h15m',
      departAirportName: '首都国际机场',
      departTerminal: 'T3',
      arriveAirportName: '天河国际机场',
      arriveTerminal: 'T2',
      flightNo: 'CA8901',
      stops: '0',
      createTime: '2024-10-05 15:30:00',
      contactName: '黄十九',
    },
    {
      orderSource: 1,
      orderBaseId: 'ORDER_018',
      flightOrderNo: 'MU456701890123',
      flightOrderType: 'FLIGHT',
      flightOrderStatus: '待出行',
      refundStatus: '0',
      refundAmount: 0,
      payExpireTime: '2024-10-14 23:59:59',
      fromCityCode: 'SHA',
      fromCityName: '上海',
      toCityCode: 'TAO',
      toCityName: '青岛',
      tripType: '1',
      fromDate: '10月15日 周一',
      returnDate: '',
      totalAmount: 880,
      payAmount: '880',
      departTime: '13:30',
      arriveTime: '15:45',
      durationTime: '2h15m',
      departAirportName: '虹桥国际机场',
      departTerminal: 'T2',
      arriveAirportName: '流亭国际机场',
      arriveTerminal: 'T1',
      flightNo: 'MU4567',
      stops: '0',
      createTime: '2024-10-08 11:20:00',
      contactName: '周二十',
    },
    {
      orderSource: 1,
      orderBaseId: 'ORDER_019',
      flightOrderNo: 'CZ567801901234',
      flightOrderType: 'FLIGHT',
      flightOrderStatus: '已完成',
      refundStatus: '0',
      refundAmount: 0,
      payExpireTime: '',
      fromCityCode: 'CAN',
      fromCityName: '广州',
      toCityCode: 'KMG',
      toCityName: '昆明',
      tripType: '1',
      fromDate: '10月18日 周四',
      returnDate: '',
      totalAmount: 1420,
      payAmount: '1420',
      departTime: '09:45',
      arriveTime: '12:30',
      durationTime: '2h45m',
      departAirportName: '白云国际机场',
      departTerminal: 'T2',
      arriveAirportName: '长水国际机场',
      arriveTerminal: 'T1',
      flightNo: 'CZ5678',
      stops: '0',
      createTime: '2024-10-11 16:00:00',
      contactName: '吴二十一',
    },
    {
      orderSource: 1,
      orderBaseId: 'ORDER_020',
      flightOrderNo: 'HU678902012345',
      flightOrderType: 'FLIGHT',
      flightOrderStatus: '待出行',
      refundStatus: '0',
      refundAmount: 0,
      payExpireTime: '2024-10-19 23:59:59',
      fromCityCode: 'DLC',
      fromCityName: '大连',
      toCityCode: 'SHA',
      toCityName: '上海',
      tripType: '1',
      fromDate: '10月20日 周六',
      returnDate: '',
      totalAmount: 960,
      payAmount: '960',
      departTime: '14:00',
      arriveTime: '16:15',
      durationTime: '2h15m',
      departAirportName: '周水子国际机场',
      departTerminal: 'T1',
      arriveAirportName: '浦东国际机场',
      arriveTerminal: 'T2',
      flightNo: 'HU6789',
      stops: '0',
      createTime: '2024-10-13 14:50:00',
      contactName: '郑二十二',
    },
    {
      orderSource: 1,
      orderBaseId: 'ORDER_021',
      flightOrderNo: 'MF890102123456',
      flightOrderType: 'FLIGHT',
      flightOrderStatus: '退款中',
      refundStatus: '1',
      refundAmount: 530,
      payExpireTime: '',
      fromCityCode: 'FOC',
      fromCityName: '福州',
      toCityCode: 'BJS',
      toCityName: '北京',
      tripType: '1',
      fromDate: '10月22日 周一',
      returnDate: '',
      totalAmount: 530,
      payAmount: '530',
      departTime: '08:00',
      arriveTime: '10:45',
      durationTime: '2h45m',
      departAirportName: '长乐国际机场',
      departTerminal: 'T2',
      arriveAirportName: '首都国际机场',
      arriveTerminal: 'T2',
      flightNo: 'MF8901',
      stops: '0',
      createTime: '2024-10-15 09:25:00',
      contactName: '冯二十三',
    },
    {
      orderSource: 1,
      orderBaseId: 'ORDER_022',
      flightOrderNo: 'ZH123402234567',
      flightOrderType: 'FLIGHT',
      flightOrderStatus: '已完成',
      refundStatus: '0',
      refundAmount: 0,
      payExpireTime: '',
      fromCityCode: 'SZX',
      fromCityName: '深圳',
      toCityCode: 'CTU',
      toCityName: '成都',
      tripType: '1',
      fromDate: '10月25日 周四',
      returnDate: '',
      totalAmount: 1180,
      payAmount: '1180',
      departTime: '16:00',
      arriveTime: '18:30',
      durationTime: '2h30m',
      departAirportName: '宝安国际机场',
      departTerminal: 'T3',
      arriveAirportName: '双流国际机场',
      arriveTerminal: 'T1',
      flightNo: 'ZH1234',
      stops: '0',
      createTime: '2024-10-18 12:40:00',
      contactName: '陈二十四',
    },
    {
      orderSource: 1,
      orderBaseId: 'ORDER_023',
      flightOrderNo: '3U234502345678',
      flightOrderType: 'FLIGHT',
      flightOrderStatus: '待出行',
      refundStatus: '0',
      refundAmount: 0,
      payExpireTime: '2024-10-27 23:59:59',
      fromCityCode: 'CKG',
      fromCityName: '重庆',
      toCityCode: 'SHA',
      toCityName: '上海',
      tripType: '1',
      fromDate: '10月28日 周日',
      returnDate: '',
      totalAmount: 990,
      payAmount: '990',
      departTime: '11:30',
      arriveTime: '14:15',
      durationTime: '2h45m',
      departAirportName: '江北国际机场',
      departTerminal: 'T3',
      arriveAirportName: '浦东国际机场',
      arriveTerminal: 'T2',
      flightNo: '3U2345',
      stops: '0',
      createTime: '2024-10-21 18:30:00',
      contactName: '褚二十五',
    },
    {
      orderSource: 1,
      orderBaseId: 'ORDER_024',
      flightOrderNo: 'SC456702456789',
      flightOrderType: 'FLIGHT',
      flightOrderStatus: '已取消',
      refundStatus: '3',
      refundAmount: 420,
      payExpireTime: '',
      fromCityCode: 'XMN',
      fromCityName: '厦门',
      toCityCode: 'TNA',
      toCityName: '济南',
      tripType: '1',
      fromDate: '10月30日 周二',
      returnDate: '',
      totalAmount: 420,
      payAmount: '420',
      departTime: '13:00',
      arriveTime: '15:30',
      durationTime: '2h30m',
      departAirportName: '高崎国际机场',
      departTerminal: 'T3',
      arriveAirportName: '遥墙国际机场',
      arriveTerminal: 'T1',
      flightNo: 'SC4567',
      stops: '0',
      createTime: '2024-10-23 10:00:00',
      contactName: '卫二十六',
    },
    {
      orderSource: 1,
      orderBaseId: 'ORDER_025',
      flightOrderNo: 'CA345602567890',
      flightOrderType: 'FLIGHT',
      flightOrderStatus: '已完成',
      refundStatus: '0',
      refundAmount: 0,
      payExpireTime: '',
      fromCityCode: 'BJS',
      fromCityName: '北京',
      toCityCode: 'CSX',
      toCityName: '长沙',
      tripType: '1',
      fromDate: '11月2日 周五',
      returnDate: '',
      totalAmount: 1320,
      payAmount: '1320',
      departTime: '10:00',
      arriveTime: '12:30',
      durationTime: '2h30m',
      departAirportName: '首都国际机场',
      departTerminal: 'T3',
      arriveAirportName: '黄花国际机场',
      arriveTerminal: 'T2',
      flightNo: 'CA3456',
      stops: '0',
      createTime: '2024-10-26 13:15:00',
      contactName: '蒋二十七',
    },
  ];

  return (
    <view className="page-order-list">
      {/* 这里可以替换为导航栏背景图 */}
      <view
        className="page-header-bg"
        style={{ opacity: inverseOpacity }}
      ></view>
      <NavBar main-thread:ref={navBarRef} title="我的订单" backgroundOpacity={opacity}></NavBar>

      {/* Orders List */}
      <List
        className="orders-list"
        listId="order-list"
        listType="single"
        scrollOrientation="vertical"
        spanCount={1}
        mainAxisGap={12}
        scrollEventThrottle={0}
        main-thread:onScroll={handleScrollMT}
      >
        {orders.map((order) => (
          <list-item
            key={order.orderBaseId}
            item-key={order.orderBaseId}
            bindtap={() => handleOrderTap(order)}
          >
            <view className="order-item">
              <view className="order-info">
                <text className="order-airline">
                  {getAirlineName(order.flightNo)} {order.flightNo}
                </text>
                <text className="order-date">{order.fromDate}</text>
              </view>
              <view className="order-route">
                <view className="order-route-point">
                  <text className="order-city">{order.fromCityName}</text>
                  <text className="order-time">{order.departTime}</text>
                </view>
                <text className="order-arrow">→</text>
                <view className="order-route-point">
                  <text className="order-city">{order.toCityName}</text>
                  <text className="order-time">{order.arriveTime}</text>
                </view>
              </view>
              <view className="order-status-row">
                <text
                  className={`order-status order-status--${order.flightOrderStatus}`}
                >
                  {order.flightOrderStatus}
                </text>
                <text className="order-price">¥{order.totalAmount}</text>
              </view>
            </view>
          </list-item>
        ))}
      </List>

      {/* Empty State */}
      {orders.length === 0 && (
        <view className="orders-empty">
          <text className="orders-empty-text">暂无订单</text>
        </view>
      )}
    </view>
  );
}
