import type { TrainInfo } from './types'

export const mockTrainList: TrainInfo[] = [
  {
    trainNo: 'G547',
    fromDate: '2026-05-23',
    toDate: '2026-05-23',
    fromTime: '06:18',
    toTime: '12:11',
    fromStation: '北京南',
    toStation: '上海虹桥',
    duration: '5时53分',
    seatDetails: [
      { seatName: '二等座', price: 626, seatCnt: 99, downPrice: 0, midPrice: 0, upPrice: 0, discount: '9.5', downDiscount: '', midDiscount: '', upDiscount: '', childPrice: 313, serviceFee: 0 },
      { seatName: '一等座', price: 1035, seatCnt: 99, downPrice: 0, midPrice: 0, upPrice: 0, discount: '9.8', downDiscount: '', midDiscount: '', upDiscount: '', childPrice: 517.5, serviceFee: 0 },
      { seatName: '商务座', price: 2318, seatCnt: 15, downPrice: 0, midPrice: 0, upPrice: 0, discount: '', downDiscount: '', midDiscount: '', upDiscount: '', childPrice: 1854.4, serviceFee: 0 },
      { seatName: '无座', price: 626, seatCnt: 99, downPrice: 0, midPrice: 0, upPrice: 0, discount: '', downDiscount: '', midDiscount: '', upDiscount: '', childPrice: 313, serviceFee: 0 },
    ],
    isQuietCoach: '1',
    isFxh: '1',
    isZndcz: '1',
    isHigh: '1',
    minPrice: 626,
    discount: '9.5',
    intervalDay: 0,
  },
  {
    trainNo: 'G1',
    fromDate: '2026-05-23',
    toDate: '2026-05-23',
    fromTime: '06:30',
    toTime: '11:24',
    fromStation: '北京南',
    toStation: '上海虹桥',
    duration: '4时54分',
    seatDetails: [
      { seatName: '二等座', price: 662, seatCnt: 99, downPrice: 0, midPrice: 0, upPrice: 0, discount: '', downDiscount: '', midDiscount: '', upDiscount: '', childPrice: 331, serviceFee: 0 },
      { seatName: '一等座', price: 1060, seatCnt: 99, downPrice: 0, midPrice: 0, upPrice: 0, discount: '', downDiscount: '', midDiscount: '', upDiscount: '', childPrice: 530, serviceFee: 0 },
      { seatName: '商务座', price: 2318, seatCnt: 11, downPrice: 0, midPrice: 0, upPrice: 0, discount: '', downDiscount: '', midDiscount: '', upDiscount: '', childPrice: 1854.4, serviceFee: 0 },
      { seatName: '无座', price: 662, seatCnt: 99, downPrice: 0, midPrice: 0, upPrice: 0, discount: '', downDiscount: '', midDiscount: '', upDiscount: '', childPrice: 331, serviceFee: 0 },
    ],
    isQuietCoach: '1',
    isFxh: '1',
    isZndcz: '0',
    isHigh: '1',
    minPrice: 662,
    discount: '',
    intervalDay: 0,
  },
  {
    trainNo: 'G3',
    fromDate: '2026-05-23',
    toDate: '2026-05-23',
    fromTime: '06:52',
    toTime: '11:33',
    fromStation: '北京南',
    toStation: '上海',
    duration: '4时41分',
    seatDetails: [
      { seatName: '二等座', price: 669, seatCnt: 99, downPrice: 0, midPrice: 0, upPrice: 0, discount: '', downDiscount: '', midDiscount: '', upDiscount: '', childPrice: 334.5, serviceFee: 0 },
      { seatName: '一等座', price: 1070, seatCnt: 5, downPrice: 0, midPrice: 0, upPrice: 0, discount: '', downDiscount: '', midDiscount: '', upDiscount: '', childPrice: 535, serviceFee: 0 },
      { seatName: '优选一等座', price: 1471, seatCnt: 12, downPrice: 0, midPrice: 0, upPrice: 0, discount: '', downDiscount: '', midDiscount: '', upDiscount: '', childPrice: 1471, serviceFee: 0 },
      { seatName: '商务座', price: 2341, seatCnt: 10, downPrice: 0, midPrice: 0, upPrice: 0, discount: '', downDiscount: '', midDiscount: '', upDiscount: '', childPrice: 1872.8, serviceFee: 0 },
      { seatName: '无座', price: 669, seatCnt: 99, downPrice: 0, midPrice: 0, upPrice: 0, discount: '', downDiscount: '', midDiscount: '', upDiscount: '', childPrice: 334.5, serviceFee: 0 },
    ],
    isQuietCoach: '1',
    isFxh: '1',
    isZndcz: '1',
    isHigh: '1',
    minPrice: 669,
    discount: '',
    intervalDay: 0,
  },
  {
    trainNo: 'G565',
    fromDate: '2026-05-23',
    toDate: '2026-05-23',
    fromTime: '07:07',
    toTime: '13:12',
    fromStation: '北京南',
    toStation: '上海虹桥',
    duration: '6时5分',
    seatDetails: [
      { seatName: '二等座', price: 626, seatCnt: 99, downPrice: 0, midPrice: 0, upPrice: 0, discount: '9.5', downDiscount: '', midDiscount: '', upDiscount: '', childPrice: 313, serviceFee: 0 },
      { seatName: '一等座', price: 1035, seatCnt: 99, downPrice: 0, midPrice: 0, upPrice: 0, discount: '9.8', downDiscount: '', midDiscount: '', upDiscount: '', childPrice: 517.5, serviceFee: 0 },
      { seatName: '商务座', price: 2318, seatCnt: 99, downPrice: 0, midPrice: 0, upPrice: 0, discount: '', downDiscount: '', midDiscount: '', upDiscount: '', childPrice: 1854.4, serviceFee: 0 },
      { seatName: '无座', price: 626, seatCnt: 99, downPrice: 0, midPrice: 0, upPrice: 0, discount: '', downDiscount: '', midDiscount: '', upDiscount: '', childPrice: 313, serviceFee: 0 },
    ],
    isQuietCoach: '1',
    isFxh: '0',
    isZndcz: '0',
    isHigh: '1',
    minPrice: 626,
    discount: '9.5',
    intervalDay: 0,
  },
  {
    trainNo: 'G5',
    fromDate: '2026-05-23',
    toDate: '2026-05-23',
    fromTime: '07:42',
    toTime: '12:32',
    fromStation: '北京',
    toStation: '上海',
    duration: '4时50分',
    seatDetails: [
      { seatName: '二等座', price: 673, seatCnt: 99, downPrice: 0, midPrice: 0, upPrice: 0, discount: '', downDiscount: '', midDiscount: '', upDiscount: '', childPrice: 336.5, serviceFee: 0 },
      { seatName: '一等座', price: 1076, seatCnt: 9, downPrice: 0, midPrice: 0, upPrice: 0, discount: '', downDiscount: '', midDiscount: '', upDiscount: '', childPrice: 538, serviceFee: 0 },
      { seatName: '商务座', price: 2354, seatCnt: 7, downPrice: 0, midPrice: 0, upPrice: 0, discount: '', downDiscount: '', midDiscount: '', upDiscount: '', childPrice: 1883.2, serviceFee: 0 },
      { seatName: '无座', price: 673, seatCnt: 99, downPrice: 0, midPrice: 0, upPrice: 0, discount: '', downDiscount: '', midDiscount: '', upDiscount: '', childPrice: 336.5, serviceFee: 0 },
    ],
    isQuietCoach: '1',
    isFxh: '1',
    isZndcz: '0',
    isHigh: '1',
    minPrice: 673,
    discount: '',
    intervalDay: 0,
  },
  {
    trainNo: 'G25',
    fromDate: '2026-05-23',
    toDate: '2026-05-23',
    fromTime: '17:00',
    toTime: '21:18',
    fromStation: '北京南',
    toStation: '上海虹桥',
    duration: '4时18分',
    seatDetails: [
      { seatName: '二等座', price: 662, seatCnt: 99, downPrice: 0, midPrice: 0, upPrice: 0, discount: '', downDiscount: '', midDiscount: '', upDiscount: '', childPrice: 331, serviceFee: 0 },
      { seatName: '一等座', price: 1060, seatCnt: 99, downPrice: 0, midPrice: 0, upPrice: 0, discount: '', downDiscount: '', midDiscount: '', upDiscount: '', childPrice: 530, serviceFee: 0 },
      { seatName: '优选一等座', price: 1457, seatCnt: 9, downPrice: 0, midPrice: 0, upPrice: 0, discount: '', downDiscount: '', midDiscount: '', upDiscount: '', childPrice: 1457, serviceFee: 0 },
      { seatName: '商务座', price: 2318, seatCnt: 14, downPrice: 0, midPrice: 0, upPrice: 0, discount: '', downDiscount: '', midDiscount: '', upDiscount: '', childPrice: 1854.4, serviceFee: 0 },
      { seatName: '无座', price: 662, seatCnt: 99, downPrice: 0, midPrice: 0, upPrice: 0, discount: '', downDiscount: '', midDiscount: '', upDiscount: '', childPrice: 331, serviceFee: 0 },
    ],
    isQuietCoach: '1',
    isFxh: '1',
    isZndcz: '1',
    isHigh: '1',
    minPrice: 662,
    discount: '',
    intervalDay: 0,
  },
  {
    trainNo: 'D17',
    fromDate: '2026-05-23',
    toDate: '2026-05-24',
    fromTime: '19:10',
    toTime: '07:31',
    fromStation: '北京',
    toStation: '上海松江',
    duration: '12时21分',
    seatDetails: [
      { seatName: '二等座', price: 367, seatCnt: 99, downPrice: 0, midPrice: 0, upPrice: 0, discount: '8', downDiscount: '', midDiscount: '', upDiscount: '', childPrice: 183.5, serviceFee: 0 },
      { seatName: '二等卧', price: 522, seatCnt: 99, downPrice: 522, midPrice: 477, upPrice: 447, discount: '6.5', downDiscount: '6.5', midDiscount: '6.5', upDiscount: '6.5', childPrice: 522, serviceFee: 0 },
      { seatName: '一等卧', price: 641, seatCnt: 99, downPrice: 641, midPrice: 0, upPrice: 566, discount: '6.5', downDiscount: '6.5', midDiscount: '', upDiscount: '6.5', childPrice: 641, serviceFee: 0 },
      { seatName: '无座', price: 367, seatCnt: 99, downPrice: 0, midPrice: 0, upPrice: 0, discount: '', downDiscount: '', midDiscount: '', upDiscount: '', childPrice: 183.5, serviceFee: 0 },
    ],
    isQuietCoach: '0',
    isFxh: '1',
    isZndcz: '0',
    isHigh: '1',
    minPrice: 367,
    discount: '8',
    intervalDay: 1,
  },
  {
    trainNo: 'Z281',
    fromDate: '2026-05-23',
    toDate: '2026-05-24',
    fromTime: '19:21',
    toTime: '08:44',
    fromStation: '北京丰台',
    toStation: '上海松江',
    duration: '13时23分',
    seatDetails: [
      { seatName: '硬座', price: 177.5, seatCnt: 0, downPrice: 0, midPrice: 0, upPrice: 0, discount: '', downDiscount: '', midDiscount: '', upDiscount: '', childPrice: 88.75, serviceFee: 0 },
      { seatName: '硬卧', price: 325.5, seatCnt: 0, downPrice: 325.5, midPrice: 315.5, upPrice: 304.5, discount: '', downDiscount: '', midDiscount: '', upDiscount: '', childPrice: 325.5, serviceFee: 0 },
      { seatName: '软卧', price: 497.5, seatCnt: 0, downPrice: 497.5, midPrice: 0, upPrice: 476.5, discount: '', downDiscount: '', midDiscount: '', upDiscount: '', childPrice: 497.5, serviceFee: 0 },
      { seatName: '无座', price: 177.5, seatCnt: 99, downPrice: 0, midPrice: 0, upPrice: 0, discount: '', downDiscount: '', midDiscount: '', upDiscount: '', childPrice: 88.75, serviceFee: 0 },
    ],
    isQuietCoach: '0',
    isFxh: '0',
    isZndcz: '0',
    isHigh: '0',
    minPrice: 177.5,
    discount: '',
    intervalDay: 1,
  },
]
